{"uuid":"ae3c7c36-a6f1-499a-8941-d8c63dfc7826","historyId":"24940fece27ef23d9a7c9ee4fd6772ea","fullName":"com.testcase.AddRoleCase.testRegister","labels":[{"name":"package","value":"com.testcase.AddRoleCase"},{"name":"testClass","value":"com.testcase.AddRoleCase"},{"name":"testMethod","value":"testRegister"},{"name":"parentSuite","value":"线上环境-自动化测试框架-mall项目-Demo"},{"name":"suite","value":"用户模块"},{"name":"subSuite","value":"com.testcase.AddRoleCase"},{"name":"host","value":"Athena"},{"name":"thread","value":"11952@Athena.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"用户模块"},{"name":"feature","value":"添加用户角色功能"}],"links":[],"name":"添加用户角色接口测试","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"断言失败：响应断言=true，SQL 断言=false did not expect to find [true] but found [false]","trace":"java.lang.AssertionError: 断言失败：响应断言=true，SQL 断言=false did not expect to find [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:969)\r\n\tat org.testng.Assert.assertTrue(Assert.java:43)\r\n\tat com.testcase.BaseCase.logFinalResult(BaseCase.java:300)\r\n\tat com.testcase.BaseCase.finishWriteBackAndAssert(BaseCase.java:220)\r\n\tat com.testcase.BaseCase.executeTestCase(BaseCase.java:128)\r\n\tat com.testcase.AddRoleCase.testRegister(AddRoleCase.java:27)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg0","value":"添加角色成功"}],"start":1744082037023,"stop":1744082037224}